### ISSUE TITLE
yaml parsing error

### ISSUE THREAD

**Issue by kimthostrup** [ajgon/self-hosted-mailserver#1]
I can't seem to figure out why /roles/maildb/vars/main.yml seem to fail, can you please verify that the default version is correct, from a yaml standard perspective ?
When trying to parse the /roles/maildb/vars/main.yml with http://yaml-online-parser.appspot.com/ it comes with the following error : 
----snip----
ERROR:

while parsing a block mapping
  in "<unicode string>", line 3, column 3:
      postmaster_email: ""
      ^
expected <block end>, but found '<block sequence start>'
  in "<unicode string>", line 13, column 5:
        - name: ""
        ^
----snip----

Thanks in advance.
/Kim

**Comment by ajgon** [comment]
Hey,

Yeah, there was a typo in the file (under domains: section - I tried to make it a string and an array simultaneously ;) ). Thanks for catching this up!

**Comment by kimthostrup** [comment]
np ;) 
thanks for putting the time and effort into this collection of tools and binding them all together, only think missing is a web interface for managing the users/domains/spam quarantine ;)
