### ISSUE TITLE
Dovecot install error

### ISSUE THREAD

**Issue by kimthostrup** [ajgon/self-hosted-mailserver#2]
Clean install on Debian 8 (with sudo installed)
Thanks in advance.
/Kim

TASK: [dovecot | /tmp/create-imap-dirs] ***************************************
fatal: [192.168.10.149] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'str object' has no attribute 'email'", 'failed': True}
fatal: [192.168.10.149] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'str object' has no attribute 'email'", 'failed': True}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/main.retry

192.168.10.149             : ok=79   changed=70   unreachable=1    failed=0

**Comment by ajgon** [comment]
Can you show me your `maildb/vars/main.yml` (with emails/passwords replaced by dummy data) ?

**Comment by kimthostrup** [comment]
here goes:

maildb:
  # This email should be a local email (i.e. listed below in users section for any domain). It will receive all failure messages from MAILER-DAEMON.
  postmaster_email: "postmaster@test.dk"
  # MySQL user username for mailserver database (use different than root!)
  username: "mailuser"
  # MySQL user password for mailserver database
  password: "GaergaerGW5Q"
  # MySQL database name for mailserver
  database: "mailserver"
  # List of mail domains (you can put as many as you like)
  domains:
      # Domain name (i.e. example.com)
    - name: "test.dk"
      # Is this primary domain (if you wish to receive PUSH notifications from it, you should set it to yes)
      primary: yes
      # List of users associated with that domain
      users: [bob bobby benny]
      # Domain name (i.e. example.com)
    - name: "test2.dk"
      # Is this primary domain (if you wish to receive PUSH notifications from it, you should set it to yes)
      primary: no
      # List of users associated with that domain
      users:
      # User email - use full email address (i.e. steven@example.com)
      - email: "test@test.dk"
      # Email password
        password: "jefwekjbckwe"

**Comment by ajgon** [comment]
Ok, I need to document better those files ;) The problem is, that you set users as array of logins for test.dk domain. That's not a format, that script expects. Under the `users` key, there always should be array of hashes, with `email` and `password` keys. So for given example, the file should like somehow like that:

```
domains:
  - name: "test.dk"
    primary: yes
    users:
      - email: "bob@test.dk"
        password: "password"
      - email: "bobby@test.dk"
        password: "password"
      - email: "benny@test.dk"
        password: "password"
```

**Comment by kimthostrup** [comment]
Sorry for the late reply, but thanks for the enlightenment ;)
